version: '3.8'

services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    image: pinsara23/supermarket-chatbot-backend:latest
    container_name: supermarket-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - ENV=production
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60
    restart: unless-stopped
